apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay

  templates:
    - name: whalesay
      container:
        # run cowsay with that message input parameter as args
        image: rancher/cowsay
        command: [cowsay]
        args: ["hello world"]
